# Generated by Django 6.0.2 on 2026-02-16 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paymentgateway_affiliate_affiliatepayout_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_child_panels',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChildPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('admin_username', models.CharField(max_length=100)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nameserver1', models.CharField(default='ns1.perfectdns.com', max_length=255)),
                ('nameserver2', models.CharField(default='ns2.perfectdns.com', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_panels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
