# Generated by Django 6.0.2 on 2026-02-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_can_create_child_panels_childpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='childpanel',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
